### PR TITLE
Add ssl tests support

### PR DESCRIPTION
**Pull request by gaalexandre**
In this PR I took @gaetanfl branch and updated it to work on the actual behaviour of the API, in particular creation of SSL tests.
Tests were also updated.

### CODE REVIEW

**Comment by croman** [comment]
Thanks for your work on this @alexandreFre. I have two small comments before merging:

- Can you replace the `fretlink.com` links with something more generic (e.g. `example.com`)?
- Running `make lint` suggests some changes in `ssl.go`, can you look into that?

**Comment by gaalexandre** [comment]
Ok i will do that.

**Comment by gaalexandre** [comment]
@croman I have taken your comment into account thanks for reviewing.

**Comment by croman** [comment]
Looks good, thanks @alexandreFre

**Pull request merged**
