### PR TITLE
Switch ContactID handling back to numeric

### PR DESCRIPTION
**Pull request by matschaffer**
As mentioned on https://github.com/DreamItGetIT/statuscake/issues/21#issuecomment-357882903 it looks like statuscake switched this around a bit again.

### CODE REVIEW

**Comment by matschaffer** [comment]
@croman any testing or verification you need help with before merging?

Looks like @AndorCS has a provider ready for the terraform provider that uses this.

**Comment by AndorCS** [comment]
Everything works for me.

**Comment by croman** [comment]
@matschaffer Looking now at the documentation, the ContactGroup field seems to be a string, do we still need this PR?

**Comment by matschaffer** [comment]
I'm pretty sure we need it yes.

@croman the main thing that needs fixing is the `ContactID` handling. 

It appears that statuscake had it as a string, you picked up that change, then they changed it back. The result is now you get marshaling errors even trying to get the state of a test.

It's possible https://github.com/DreamItGetIT/statuscake/pull/24/files#diff-8e127cb80ec48370b10e1df7579a97baR107 is not a change that needs to happen, but seemed cleaner to undo the previous change in its entirety.

**Comment by croman** [comment]
thanks @matschaffer, merged.

**Pull request merged**
