### PR TITLE
 allow for filtering when retrieving tests from status cake

### PR DESCRIPTION
**Pull request by kodieGlosser**
Additionally adding an easy way to get deps as I did not see any added :)

### CODE REVIEW

**Comment by kodieGlosser** [comment]
@opas3n mind taking a look at my PR? I Would like to implement this to use in our own packages.

**Comment by croman** [comment]
@kodieGlosser Why did you choose `glide` over `dep`? Seems that `glide` is not maintained anymore and they are advising users to migrate to `dep`.

**Comment by kodieGlosser** [comment]
Interesting, I didnt even know that! I'll make the switch over to dep

**Comment by kodieGlosser** [comment]
@croman ok now we are using deps!

**Pull request merged**
