### PR TITLE
Adding PostRaw option

### PR DESCRIPTION
**Pull request by bkvaluemeal**
This is an undocumented feature that StatusCake provides

### CODE REVIEW

**Comment by croman** [comment]
Why is that feature not documented? @bkvaluemeal

**Comment by bkvaluemeal** [comment]
That's a great question. I don't know. I assume that StatusCake just forgot??
[https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md](https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md)

**Comment by bkvaluemeal** [comment]
@croman I was able to get StatusCake to update their documentation. They have added PostRaw to the list of available options.

**Comment by croman** [comment]
Looks good. Thanks @bkvaluemeal

**Pull request merged**
