### PR TITLE
Update statuscake api url

### PR DESCRIPTION
**Pull request by ldjohnson**
Updating the url for statuscake's api as it has changed.

### CODE REVIEW

**Comment by hobochili** [comment]
Was just about to submit the same. For reference, I received this response back from StatusCake support this morning:

> Hey there, the last [API] change was a few weeks back, but we did make some changes to our redirects yesterday, statuscake.com/App links were changed a few months back and will no longer work, so the choice would be to edit your script to the proper app.statuscake.com links shown on the API - or to enable redirects.

**Comment by gwhitelaw** [comment]
Thanks for that. Your last PR (#4) introduced a failed test which I fixed in #7. Please can you update the tests for this PR too and then I'll merge.

Cheers.

**Comment by stack72** [comment]
Thanks for staying on top here @gwhitelaw :) <3 you all!

**Comment by ldjohnson** [comment]
@gwhitelaw Sorry about that.  I didn't mean to leave the tests failing like that.  I'll remember to update those moving forward.

I brought this PR up-to-date with master and updated the tests to use the new URL.

Please let me know if have any questions or concerns or if you need anything else.

**Comment by gwhitelaw** [comment]
Not a problem @ldjohnson :) Code all looks good to me!

lets merge

**Pull request merged**
