### PR TITLE
WIP: first try of ssl implementation

### PR DESCRIPTION
**Pull request by gaetanfl**
This PR lacks of documentation and update test because of API limitation and my laziness to implement a two calls mockup of apiclient.

### CODE REVIEW

**Comment by gaetanfl** [comment]
Checkrate is not returned by the get api so it's ignored

**Comment by gaetanfl** [comment]
API documentation is wrong for update response.

**Comment by ivanschwarz** [comment]
@gaetanfl Are you planning to continue working on this PR? Quite some people would welcome this feature (see #32 , terraform-providers/terraform-provider-statuscake#6).

**Comment by gaetanfl** [comment]
Actually I was caiting for a change on statuscake API which was made but my priorities shifted at jib. I may go back to it in two weeks.

**Comment by gaetanfl** [comment]
This PR has been superseded by #42 .I'm closing it

**Pull request closed without merging**
